#!/bin/bash

#Gathers an average of the Idle CPU usage load from the output of sar gathered every 15 minutes

IDLE=`more /Library/Scripts/BellMedia/sargathering | grep Average | awk 'BEGIN{s=0;}{s=s+$5;}END{print s/NR;}' | awk '{printf("%d\n",$0+=$0<0?-0.5:0.5)}'`

echo "<result>$IDLE</result>"