#!/bin/bash

#Gathers an average of the User CPU usage load from the output of sar gathered every 15 minutes

USR=`more /Users/Shared/sargathering | grep Average | awk 'BEGIN{s=0;}{s=s+$2;}END{print s/NR;}' | awk '{printf("%d\n",$0+=$0<0?-0.5:0.5)}'`

echo "<result>$USR</result>"